### PR TITLE
PCHR-1514: Changed CiviCRM logo to CiviHR

### PR DESCRIPTION
**Pull request by deb1990**
# Requirement
Replace the CiviCRM logo in the navigation with the CiviHR logo

**Before**
image

**After**
image

### CODE REVIEW

**Comment by brunoqueiros** [comment]
Approved!

**Comment by JonScreat** [comment]
I think just having the logo mark without the text may look nicer and fit better.

logomark

**Comment by omarabuhussein** [comment]
yes hrnavigation get replaced by hrui in this PR https://github.com/civicrm/civihr/pull/1149 , but don't worry I will apply your changes on my PR after it pass testing .

**Comment by AkA84** [comment]
Approved

**Pull request merged**
