### PR TITLE
PCHR-565: Dashboard (static)

### PR DESCRIPTION
**Pull request by AkA84**
##### Dashboard
page

##### "Add Appraisal Cycle" modal
modal

#### .btn-group
btn-group

* Added a fixed horizontal padding to the buttons in the button group
* Manually aligned the `.btn-group` inside a `.panel-heading`

#### .btn-default
button-default
```html
<button class="btn btn-default ">Default button</button>
```

The `btn-default` variation has a drop shadow and no border

#### .panel-title-sm
The `.panel-title-sm` variation of the standard `.panel-title` is to be used when the title of a `panel` should be smaller (`16px` instead of `18px`)

#### .dropdown-menu
dropdown-menu

Customised the appearance of the dropdown menu in terms of padding and colors

#### Forms
form

* `<label>`s are always aligned to the left and, when included in `.form-group-sm` they retain the default `font-size`

#### Modal
Customised the look-and-feel of the Bootstrap modal (see screenshot above)

#### Font Awesome
Added 3 utility classes for Font Awesome
1. `.fa-0_5x` - Set the icon to a fixed `font-size` of `9px` (`$font-size-xs`)
2. `.fa-1x` - Set the icon to a fixed `font-size` of `13px` (`$font-size-base`)
3. `.fa-color-primary` - Set the color of the icon to `$brand-primary`

#### .dl-inline
dl-inline
```html
<dl class="dl-inline">
    <dt>Term #1:</dt>
    <dd>Definition #1</dd>
    <dt>Term #2:</dt>
    <dd>Definition #2</dd>
    <dt>Term #3:</dt>
    <dd>Definition #3</dd>
</dl>
```
A `<dl>` whose elements are all inline one after the other

#### chart color utility classes
* The `.chart-color-{index}` class has also the `border-color` property set

2 new utility classes have been added

1. `.chart-color-bg-{index}` - Only sets the background with the chart color
2. `.chart-color-border-{index}` - Only sets the border with the chart color

#### .chr_appraisals-cycle-summary
chr_appraisal-cycle-summary

It's basically a custom class used to lay out the left hand side elements in the `.panel-heading` section

##### Default version
chr_steps
```html
<ul class="list-unstyled chr_steps">
    <li class="chr_steps__step chr_steps__step--danger">
        <span class="chr_steps__step__arrow">Step 1</span>
    </li>
    <li class="chr_steps__step chr_steps__step--primary">
        <span class="chr_steps__step__arrow">Step 2</span>
    </li>
    <li class="chr_steps__step">
        <span class="chr_steps__step__arrow">Step 3</span>
    </li>
    <li class="chr_steps__step">
        <span class="chr_steps__step__arrow">Step 4</span>
    </li>
    <li class="chr_steps__step">
        <span class="chr_steps__step__arrow">Step 5</span>
    </li>
</ul>
```
This component is used to display a series of "steps" in the form of labeled arrows

##### Compact version
chr_steps--compact
```html
<ul class="list-unstyled chr_steps chr_steps--compact">
    <li class="chr_steps__step chr_steps__step--danger">
        <span class="chr_steps__step__arrow">Step 1</span>
    </li>
    <li class="chr_steps__step chr_steps__step--primary">
        <span class="chr_steps__step__arrow">Step 2</span>
    </li>
    <li class="chr_steps__step">
        <span class="chr_steps__step__arrow">Step 3</span>
    </li>
    <li class="chr_steps__step">
        <span class="chr_steps__step__arrow">Step 4</span>
    </li>
    <li class="chr_steps__step">
        <span class="chr_steps__step__arrow">Step 5</span>
    </li>
</ul>
```
This modifier is to "compact" a bit the arrows, reducing the `font-size` and `padding` of the arrows

##### With legend
chr_steps-w-legend

```html
<ul class="list-unstyled chr_steps">
    <li class="chr_steps__step chr_steps__step--danger">
        <span class="chr_steps__step__arrow">Step 1</span>
        <div class="chr_steps__step__legend">
            <div class="chr_steps__step__legend__content text-center">
                <p>Lorem ipsum</p><p>Dolor sit</p><p>Amet</p>
            </div>
        </div>
    </li>
    <li class="chr_steps__step chr_steps__step--primary">
        <span class="chr_steps__step__arrow">Step 2</span>
        <div class="chr_steps__step__legend">
            <div class="chr_steps__step__legend__content text-center">
                <p>Lorem ipsum</p><p>Dolor sit</p><p>Amet</p>
            </div>
        </div>
    </li>
    <li class="chr_steps__step">
        <span class="chr_steps__step__arrow">Step 3</span>
        <div class="chr_steps__step__legend">
            <div class="chr_steps__step__legend__content text-center">
                <p>Lorem ipsum</p><p>Dolor sit</p><p>Amet</p>
            </div>
        </div>
    </li>
    <li class="chr_steps__step">
        <span class="chr_steps__step__arrow">Step 4</span>
        <div class="chr_steps__step__legend">
            <div class="chr_steps__step__legend__content text-center">
                <p>Lorem ipsum</p><p>Dolor sit</p><p>Amet</p>
            </div>
        </div>
    </li>
    <li class="chr_steps__step">
        <span class="chr_steps__step__arrow">Step 5</span>
        <div class="chr_steps__step__legend">
            <div class="chr_steps__step__legend__content text-center">
                <p>Lorem ipsum</p><p>Dolor sit</p><p>Amet</p>
            </div>
        </div>
    </li>
</ul>
```
It is possible to add a legend to each step

### CODE REVIEW

**Comment by jamienovick** [comment]
looks great. quick point that access shouldnt be on the create appraisal screen. can you check you are working from latest designs, thanks

**Comment by AkA84** [comment]
@jamienovick you are talking about the fact that you access the page via the "Appraisals" tab? If so it's something that I'm already aware of and that was discussed in this week's standup. I decided that would've been quicker to just first finish the html + css and then move everything on the correct page (kacper already prepared the empty page and the new top nav link), I'll create a ticket for it on Monday

**Comment by jamienovick** [comment]
no actually i see its an oversight that hasnt been updated in the designs.
I created a new jira for jon - it should be a very quick tweak to remove
the field to select the access settings from the create new appraisals
screen. can chat monday if any confusion.

**Comment by kkalamarski** [comment]
Approved

**Pull request merged**
