### PR TITLE
PCHR-1685: Update footer info

### PR DESCRIPTION
**Pull request by sleekvick**
# Old Footer

The old footer didn't have a logo and a link to https://civihr.org

civihr_version

# Iconmoon for logo

The logo at the bottom is from the iconmoon font, in the css the icon-logo class is used to reference to icon.

# Update footer info

The footer now contains the logo and a link to the https://civihr.org.

## Admin Footer
screen shot 2017-01-16 at 5 32 35 pm

## Dashboard footer

screen shot 2017-01-16 at 5 23 08 pm

### CODE REVIEW

**Comment by mi-kon** [comment]
1. Remove civicrm mentioning
2. Add screenshots from both Drupal and CiviCRM pages
3. Add line breaks where necessary to make this look nicer.
4. Ask Jon to review this PR

**Comment by JonScreat** [comment]
Is there a reason why the links are showing as two different colours? Links should be #42AFCB

**Comment by mi-kon** [comment]
@sleekvick if the last screenshot is correct, you left civicrm version (which is overridden  to say 'civihr') but hid the actual civihr version. So it should show Civihr version (the current is 1.6.5)

**Comment by sleekvick** [comment]
@JonScreat Visited links are different colors from Active links

**Comment by JonScreat** [comment]
@sleekvick can we get rid of the colour change from visited links in that case? I don't think it's needed.

**Pull request merged**
