### PR TITLE
PCHR-871-creating-additional-BAO-appraisal-validation-method

### PR DESCRIPTION
**Pull request by coldrunKacper**
I've created a new 'validateNewAppraisal()' static method which is executed every time we try to create new Appraisal. The method check for some requirements plus there is a new one which checks if there is already existing Appraisal for given Contact and Cycle ID.
We assume that Contact can have only single Appraisal per Cycle so if there is already current Appraisal existing for given Contact and Cycle then an exception is thrown.

### CODE REVIEW

**Comment by davialexandre** [comment]
@coldrunKacper Approved
I believe this will work only for new appraisals, right? Are you going to change anything in the SSP dashboard code to fix the error where Appraisal Cycles already have more than one Appraisal?

**Comment by coldrunKacper** [comment]
Yeah, I was thinking about it but don't see any solution to handle currently existing multiple appraisals per cycle / contact. @AkA84 do you think we should have some kind of Upgrader function deleting all duplicated appraisals excepting the newest (or oldest)?

**Comment by AkA84** [comment]
@coldrunKacper yes that would work, I believe it's better to keep the newest appraisal

**Comment by coldrunKacper** [comment]
Added the Upgrader function removing multiple Appraisals per Contact per Appraisal Cycle.

**Comment by davialexandre** [comment]
@coldrunKacper approved

**Pull request merged**
