### PR TITLE
PCHR-2714: Leave Calendar's tooltips

### PR DESCRIPTION
**Pull request by reneolivo**
## Overview
This PR adds a descriptive tooltip for leave requests inside the leave calendar.

This PR is related to https://github.com/compucorp/org.civicrm.shoreditch/pull/61

## Before
anim

## After
anim

### Requests

1. Holiday / Vacation - Oct 1 ~ Oct 7 - All Day
2. Holiday / Vacation - Oct 11 Half Day PM ~ Oct 13 Half Day AM
3. Out for Icecream - Oct 18 - From X time to X time
4. Out for Icecream - Oct 19 - From X time to X time
4. Out for Icecream - Oct 26 - From X time to X time
5. Holiday / Vacation - Oct 27 - Half Day AM
6. Out for Icecream - Oct 30 X time ~ Oct 31 X time

### Passing Support Data
The data for absence types, calculation units, and date types is loaded on the leave calendar component.

To load the calculation units, missing mock data was added to the [option group mocks](https://github.com/civicrm/civihr/pull/2251/commits/a2d0aad88185b720e2ae6a94542bf81986c33b45#diff-d25687063f2a4e4a8bb2b998bfc875a3). Missing tests for support data were also added ([here](https://github.com/civicrm/civihr/pull/2251/commits/a2d0aad88185b720e2ae6a94542bf81986c33b45#diff-333e6c3beacc230ca218ee76bc1006c3R124)).

The support data was passed to the leave calendar day component ([here](https://github.com/civicrm/civihr/pull/2251/commits/ce3a711d3494f31dbaacb8fd05c9fd9bfd490937#diff-621386122817c652eb3e7eabf5e163edR53)) so it can map the data for the tooltip onto the leave request.

### Mapping the data

Since the leaveRequest property of contactData is not available when the leave calendar day component starts, `$scope.$watch` was used to wait for the leave request data to be ready for manipulation:

```js
$scope.$watch('day.contactData.leaveRequest', function () {
  if (vm.contactData.leaveRequest) {
    mapLeaveRequestFields(); // maps absence types and day types into the leave request
    findAbsenceTypeCalculationUnit(); // finds the calculation unit for the leave request absence type
    selectTooltipTemplate(); // selects the tooltip template based on the calculation unit (days, hours) and date ranges (singe date, multiple dates)
  }
});
```

### Displaying the tooltip

[UI Bootstrap's Toolip](https://angular-ui.github.io/bootstrap/#!#tooltip) was used to display the tooltip. This directive has the advantage of allowing templates to be provided to use for rendering the tooltip.

A serie of tooltip templates were created for each one of these four options:

* requests for a single date, calculated in days
download 95
* requests for multiple dates, calculated in days
download 96
* requests for a single date, calculated in hours
download 97
* requests for multiple dates, calculated in hours
download 98

**Note:** Please ignore the `00:00` in the screenshots, this is because the time parameter is not being passed to the date filter. This should be fixed once `from_date` and `to_date` include the time portion.

A template would look like this:

```html
<script type="text/ng-template" id="type-days-on-multiple-dates-tooltip">
  <div>
    <strong>{{day.contactData.leaveRequest['type_id.title']}}</strong>
    <p>
      From: {{day.contactData.leaveRequest.from_date | date:'dd MMM yyyy'}},
      {{day.contactData.leaveRequest['from_date_type.label']}}<br />
      To: {{day.contactData.leaveRequest.to_date | date:'dd MMM yyyy'}},
      {{day.contactData.leaveRequest['to_date_type.label']}}
    </p>
  </div>
</script>
```

### Selecting the template
After the calculation unit for this leave request is determined, the tooltip template to use is selected using the following formula:

```js
function selectTooltipTemplate () {
  var dateRangeType, isSameDay;

  isSameDay = moment(vm.contactData.leaveRequest.from_date)
    .isSame(vm.contactData.leaveRequest.to_date, 'day');
  dateRangeType = isSameDay ? 'single-date' : 'multiple-dates';

  vm.tooltipTemplate = 'type-' + calculationUnit.name + '-on-' +
    dateRangeType + '-tooltip';
}
```

`vm.tooltipTemplate` would be used in the view to select the tooltip template: `uib-tooltip-template="day.tooltipTemplate"`

### CODE REVIEW

**Comment by igorpavlov** [comment]
@Rene, as per the After GIF - is 00:00 a placeholder or is it just because 00:00 is something set in the database?

**Comment by igorpavlov** [comment]
This one looks like "hours" type, I am not sure why it says "PM" and "AM" then. 
image

Could we please confirm if it is expected?

**Comment by igorpavlov** [comment]
@rene was it smoke tested with some edge cases like a request with a dates 15-05-2017 - 15-07-2017 ?

**Comment by reneolivo** [comment]
> This one looks like "hours" type, I am not sure why it says "PM" and "AM" then.

I created the leave request using the Leave Calendar Modal and there were no options for hours. So this is "expected for now" until hours can be selected in the modal.

**Comment by reneolivo** [comment]
## New changes

Requests for hours now display their start if the calendar day's date is the same as the start date of the request, or the end time if the date is the same as the end date for the request.

### After
download

### Technical details
The logic for displaying labels was moved from the view and into the component's controller. After the calculation unit has been determined, the label is generated using the following rules:

* If the request is an Accrued TOIL, it displays **AT**.
* if the request is for half a day AM, it displays **AM**
* if the request is for half a day PM, it displays **PM**
* if the request is for hours and the date is the start date of the request, it will display the start time of the request.
* if the request is for hours and the date is the end date of the request, it will display the end time of the request.
* if the request is for a full day, or if the date is in between the from and to dates of the request, it displays nothing.

The label generation was split into three groups: resolve label for Accrued TOIL, resolve label for days, resolve label for hours:

```js
function resolveDayLabel () {
  if (vm.contactData.isAccruedTOIL) {
    vm.label = 'AT';
  } else if (calculationUnit.name === 'days') {
    resolveDayLabelForDaysCalculationUnit();
  } else {
    resolveDayLabelForHoursCalculationUnit();
  }
}
```

For requests calculated in days the label is generated as follows:

```js
function resolveDayLabelForDaysCalculationUnit () {
  vm.label = vm.contactData.isAM ? 'AM'
    : vm.contactData.isPM ? 'PM'
    : '';
}
```

For requests calculated in hours, the label is generated as follows:

```js
function resolveDayLabelForHoursCalculationUnit () {
  var sameDateAsFromDate = moment(vm.contactData.leaveRequest.from_date)
    .isSame(vm.date, 'day');
  var sameDateAsToDate = moment(vm.contactData.leaveRequest.to_date)
    .isSame(vm.date, 'day');

  vm.label = sameDateAsFromDate
    ? moment(vm.contactData.leaveRequest.from_date).format('HH:mm')
    : sameDateAsToDate
    ? moment(vm.contactData.leaveRequest.to_date).format('HH:mm')
    : '';
}
```

In order to determine if the calendar day's date is equal to the start or end date of the request, the date value needed to be passed from the calendar month component:

```html
<leave-calendar-day
  contact-data="day.contactsData[contact.id]"
  date="day.date" <--- here
  support-data="month.supportData"
  ng-class="{ 'chr_leave-calendar__item--disabled': !day.enabled }"
></leave-calendar-day>
```

**Comment by reneolivo** [comment]
> @rene was it smoke tested with some edge cases like a request with a dates 15-05-2017 - 15-07-2017 ?

@igorpavlov these cases work as expected

download

**Pull request merged**
