### PR TITLE
PCHR-1151: Unset already exist case types in hrcase extenison

### PR DESCRIPTION
**Pull request by omarabuhussein**
https://github.com/civicrm/civihr/pull/961

### CODE REVIEW

**Comment by AkA84** [comment]
@omarabuhussein what's the holdup that prevents you to merge this PR?

**Comment by omarabuhussein** [comment]
because the develop branch was frozen ...

**Comment by AkA84** [comment]
Right, sorry forgot about that. Sure, you can merge!

**Comment by AkA84** [comment]
Merging on behalf of @omarabuhussein

**Pull request merged**
