### PR TITLE
PCHR-1576: Change style of CiviCRM menu

### PR DESCRIPTION
**Pull request by deb1990**
# Requirement
1. Fix menu height, make menu item hover state and delimiter take full height of the menu, so red area on the screenshot, instead of how it is right now.
image-2016-09-16-10-13-03-633

# After
image

### CODE REVIEW

**Comment by AkA84** [comment]
Are we sure we want this? the hover state of the menu item is supposed to be like that (see [here](http://dmaster.demo.civicrm.org/civicrm/dashboard)

To be honest this solution doesn't look right at all, now the nav items go all the way down but the text now is not vertically centered anymore and the search bar also looks decentered

**Comment by JonScreat** [comment]
I agree with Alessandro here. It looks odd to not have the text centrally aligned.

**Comment by mi-kon** [comment]
Tbh, I don't like how civicrm menu looks either, it looks odd to me as well.  But I also agree that the alignment is off now and that's not good. Let's hold off merging this fix i guess...

**Comment by deb1990** [comment]
Should I center the text and searchbar vertically?

**Pull request merged**
