### PR TITLE
PCHR-1518: adding a pre-commit hook to run civilint

### PR DESCRIPTION
**Pull request by omarabuhussein**
A pre-commit hook added to bin directory to run civilint to check for any code standards violation for any uncommitted files .

To make this hook work for you locally you need to copy it to **.git/hooks** directory in your local civihr folder.

----------------------------------------------

## More Details 

To ensure that your changes adhere to coding standards before committing them you need to run **civilint** on staged files to ensure  that there is no code  violations before committing the changes.

 To make your life easier, This git pre-commit hook will do that for you every time you run (git commit) command.  

### Setup:

- Copy **bin/pre-commit** to civihr repo **.git/hooks/** inside your local civihr site.  

selection_139

### Usage : 

Suppose you  are working on a branch feature branch called **PCHR-501-sample-data-extension**  and suppose you have one modified and staged file and one modified but not staged file as you can see in the picture below :

selection_138

Then If you run :

```bash
git commit -m "Update something ..."
```

And in case the staged file contain some code standard violations then the following errors will appear showing you where the violations are and your code will not be committed :

....Add pic here...

Hence that you didn't get any warning from the not staged file because the pre-hook script will only check staged files .

Now You can go through these errors one by one and fix them , And after you are done you can commit your work :

```bash
git commit -m "Update something ..."
```

....Add pic here...

### CODE REVIEW

**Comment by AkA84** [comment]
`civilint` will be run only on the files that are about to be committed?

**Comment by omarabuhussein** [comment]
@AkA84  Yes , but it will show all code violations in the uncommitted files even the part you didn't touched ... so you will end up fixing some old code standard violations but once all the repo is adhere to the new standard it will not be a big problem.

**Comment by omarabuhussein** [comment]
not sure why it is not working anymore as expected and check even the non-staged files .. need to investigate why .

**Comment by davialexandre** [comment]
Closing this, as no work has been done here in more than one year. Now that we have Jenkins, it probably makes more sense to run civilint with it rather than with git hooks

**Pull request closed without merging**
