### PR TITLE
PCHR-2215: System now redirects to Manage Leave Entitlements after creating a contract

### PR DESCRIPTION
**Pull request by igorpavlov**
## Overview

When you created a contract you were not redirected to Manage Leave Entitlement page. Now you are.

## Before

With the debug mode off, when you created a contract you were not redirected to Manage Leave Entitlement page.

new

## After

Now, with the debug mode off, when you create a contract you are redirected to Manage Leave Entitlement page.

new2

## Technical Details

When debugging is ON, the source files are used, when debugging OFF, the minified files are used. Updating js/dist/job-contract.min.js by running gulp in the hrjobcontractjs folder fixed the issue.

## Comments

- Tests are failing at the moment because of the bug in the test files, the bug is not related to the changes in the current PR as there is the same behaviour on https://github.com/civicrm/civihr/tree/la-milestone-3 branch. This will be fixed later.
- In this PR there is a commit (https://github.com/civicrm/civihr/pull/1915/commits/533c676ade25d228e1adf7aac5a48adec6000cf4) containing fixes that are related to another PR (https://github.com/civicrm/civihr/pull/1907)

---

-  [ ] Tests Passed

### CODE REVIEW

**Comment by igorpavlov** [comment]
@davialexandre the default text in the just made PR suggest:

## Before
_The current status. Please provide screenshots or gifs ([LICEcap](http://www.cockos.com/licecap/), [SilentCast](https://github.com/colinkeenan/silentcast)) where appropriate._

## After
_What has been changed. Please provide screenshots or gifs ([LICEcap](http://www.cockos.com/licecap/), [SilentCast](https://github.com/colinkeenan/silentcast)) where appropriate._

I though GIFs would be enough. This probably needs to be amended to avoid the confusion in the future.

**Comment by igorpavlov** [comment]
@davialexandre what to do if test are not passed (the min.js file is generated though) during gulp?

**Comment by igorpavlov** [comment]
@davialexandre done. 

The tests are failing though due to a separate bug - @AkA84 suggested to ignore it for now. 

Also, in this PR there is a commit related to another task, I forgot to run tests and include a dist file for https://compucorp.atlassian.net/browse/PCHR-2238 - @AkA84 allowed me to include fixes in this PR.

**Comment by davialexandre** [comment]
@igorpavlov looks better now. Thanks

About the failing tests, please add a note to the PR description saying why they are failing and that this will be fixed later.

In cases like this, where you're including things missing from another PR, you should use the Comments section to mention it

**Pull request merged**
